### ISSUE TITLE
combined_diff outputs two opening tags but only one closing tag when attributes are changed

### ISSUE THREAD

**Issue by Mr0grog** [anastasia/htmldiffer#28]
If the same element name was used but had different attributes, the opening tag of the element is repeated in the `combined_diff` (one for each side of the diff), but the closing tag is only output once (ostensibly because it is the same):

```py
d = diff.HTMLDiffer('<a href="somewhere">Yeah</a>', '<a href="elsewhere">Yeah</a>')
d.combined_diff
# '<a href="somewhere"><a href="elsewhere">Yeah</a>'
# ^ Note two `<a...>`, but only one `</a>`
```

Or:

```py
d = diff.HTMLDiffer('<div title="somewhere">Yeah and!</div>', '<div title="elsewhere">Yeah and.</div>')
d.combined_diff
# '<div title="somewhere"><div title="elsewhere">Yeah <span class="diff_delete">and!</span><span class="diff_insert">and.</span></div>'
```

**Comment by anastasia** [comment]
Using BeautifulSoup to fix any combined_diff generated inconsistencies.
```python
d = diff.HTMLDiffer('<a href="somewhere">Yeah</a>', '<a href="elsewhere">Yeah</a>')
d.combined_diff
# '<a class="htmldiffer-tag-change_delete" href="somewhere"><a class="htmldiffer-tag-change_insert" href="elsewhere">Yeah</a></a>'

d = diff.HTMLDiffer('<div title="somewhere">Yeah and!</div>', '<div title="elsewhere">Yeah and.</div>')
d.combined_diff
# '<div class="htmldiffer-tag-change_delete" title="somewhere"><div class="htmldiffer-tag-change_insert" title="elsewhere">Yeah <span class="htmldiffer_delete">and!</span><span class="htmldiffer_insert">and.</span></div></div>'
```

**Comment by Mr0grog** [comment]
My main concern on seeing this is that I can envision a lot of simple scenarios where it will make CSS styling look pretty screwy. e.g. if the second example above was styled with:

```css
/* Realistically, the <div> would have had a class or ID to key off of rather than this, but for the sake of example… */
[title="somewhere"], [title="elsewhere"] {
  border: 1px solid gray;
  padding: 2em;
}
```

Then you’d wind up having the text doubly inset with two gray outlines instead of one. But this does at least fix the specific issue of invalid HTML, so thanks very much for that! 👍

**Comment by anastasia** [comment]
This is mainly why I prefer the split view over the combined view. Combined views have the flaw of mutating the structure of HTML and cases like this are probably pretty common. I saw you guys are working on another differ, I would love to see a solution to this (I can only imagine it being a custom version of the difflib parser that is both HTML and CSS aware, able to do rule checking on the CSS and backtracking through HMTL in order to correct for any mishaps). Beautifulsoup seems to be an ok shortcut for the time being, but mostly I'm concentrating on split views right now (they've been most handy so far). If you have ideas, I'd love to hear about them. If you make progress on your html differ I'd love to include it in the WARC comparison dashboard.
